import {
  Organization,
  Facility,
  UserProfile,
  Role,
  Medicine,
  MedicineBatch,
  Prescription,
  DispensingRecord,
  Organism,
  Specimen,
  SusceptibilityResult,
  Alert,
  Investigation,
  SurveillanceReport,
  AuditLog,
  DataQualityIssue,
  GeographicRegion,
  PrescriberAnalytics,
  IndicationBreakdown,
  SystemConnector,
  BackgroundJob,
} from '@/types';

export const DEMO_BANNER_TEXT = "DEMO / SYNTHETIC DATA — NOT REAL PATIENT DATA";

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'MediGuard National Surveillance Network',
    type: 'hospital_network',
    country: 'Pakistan',
    region: 'Punjab',
    timezone: 'Asia/Karachi',
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'org-2',
    name: 'CityCare Healthcare System (Isolated Tenant)',
    type: 'hospital_network',
    country: 'Pakistan',
    region: 'Sindh',
    timezone: 'Asia/Karachi',
    status: 'active',
    created_at: '2024-02-01T00:00:00Z',
  },
];

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'fac-1',
    organization_id: 'org-1',
    name: 'Mayo Memorial Hospital',
    type: 'hospital',
    area: 'Central Lahore',
    address: 'Hospital Road, Anarkali, Lahore',
    status: 'active',
  },
  {
    id: 'fac-2',
    organization_id: 'org-1',
    name: 'Central Microbiology Reference Lab',
    type: 'laboratory',
    area: 'Gulberg III, Lahore',
    address: 'Main Boulevard, Gulberg, Lahore',
    status: 'active',
  },
  {
    id: 'fac-3',
    organization_id: 'org-1',
    name: 'Allama Iqbal Medical Complex',
    type: 'hospital',
    area: 'Faisal Town, Lahore',
    address: 'Allama Iqbal Town, Lahore',
    status: 'active',
  },
  {
    id: 'fac-4',
    organization_id: 'org-1',
    name: 'Regional Pharmacy Hub 01',
    type: 'pharmacy',
    area: 'Cantt, Lahore',
    address: 'Mall Road, Cantt, Lahore',
    status: 'active',
  },
  // Isolated Org 2 facilities
  {
    id: 'fac-5',
    organization_id: 'org-2',
    name: 'CityCare Karachi General',
    type: 'hospital',
    area: 'Clifton, Karachi',
    address: 'Khayaban-e-Iqbal, Clifton, Karachi',
    status: 'active',
  },
  {
    id: 'fac-6',
    organization_id: 'org-2',
    name: 'CityCare South Diagnostics',
    type: 'laboratory',
    area: 'Saddar, Karachi',
    address: 'Saddar Town, Karachi',
    status: 'active',
  },
];

export const INITIAL_ROLES: Role[] = [
  { id: 'role-1', name: 'Platform Administrator', slug: 'platform-admin', description: 'Full platform management and global reference oversight' },
  { id: 'role-2', name: 'Organization Administrator', slug: 'org-admin', description: 'Manages facilities, users, and organizational settings' },
  { id: 'role-3', name: 'Clinical Surveillance Officer', slug: 'surveillance-officer', description: 'Oversees safety signals, alerts, and investigations' },
  { id: 'role-4', name: 'Doctor / Prescriber', slug: 'doctor', description: 'Prescribes medication and reviews microbiological AST results' },
  { id: 'role-5', name: 'Pharmacist', slug: 'pharmacist', description: 'Dispenses medicines, verifies batches, and monitors repeat patterns' },
  { id: 'role-6', name: 'Laboratory Scientist', slug: 'lab-scientist', description: 'Logs specimens, pathogen cultures, and AST susceptibility data' },
  { id: 'role-7', name: 'Infection Prevention / Stewardship Professional', slug: 'stewardship-lead', description: 'Monitors AWaRe compliance and antibiotic consumption' },
  { id: 'role-8', name: 'Public Health / Epidemiology Analyst', slug: 'epidemiologist', description: 'Analyzes multi-facility and regional epidemiological trends' },
  { id: 'role-9', name: 'Read-only Executive / Researcher', slug: 'read-only', description: 'Views surveillance dashboards and published reports' },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-1',
    full_name: 'Dr. Tariq Mehmood',
    email: 'tariq.admin@mediguard.org',
    title: 'Platform Administrator & System Director',
    status: 'active',
  },
  {
    id: 'usr-2',
    full_name: 'Dr. Sarah Farooq',
    email: 'sarah.doc@mediguard.org',
    title: 'Senior Consultant Physician',
    status: 'active',
  },
  {
    id: 'usr-3',
    full_name: 'Zainab Qureshi, PharmD',
    email: 'zainab.pharm@mediguard.org',
    title: 'Lead Clinical Pharmacist',
    status: 'active',
  },
  {
    id: 'usr-4',
    full_name: 'Dr. Asad Ullah, PhD',
    email: 'asad.lab@mediguard.org',
    title: 'Principal Clinical Microbiologist',
    status: 'active',
  },
  {
    id: 'usr-5',
    full_name: 'Ayesha Malik, MPH',
    email: 'ayesha.analyst@mediguard.org',
    title: 'Antimicrobial Stewardship Officer',
    status: 'active',
  },
  {
    id: 'usr-6',
    full_name: 'Bilal Hassan',
    email: 'bilal.epi@mediguard.org',
    title: 'Senior Epidemiology Analyst',
    status: 'active',
  },
  {
    id: 'usr-7',
    full_name: 'Dr. Maria Khan',
    email: 'maria.research@mediguard.org',
    title: 'Health Systems Researcher',
    status: 'active',
  },
];

export const INITIAL_MEDICINES: Medicine[] = [
  {
    id: 'med-1',
    generic_name: 'Amoxicillin / Clavulanic Acid',
    brand_name: 'Augmentin',
    active_ingredients: 'Amoxicillin 500mg, Clavulanic Acid 125mg',
    strength: '625 mg',
    dosage_form: 'Tablet',
    route: 'Oral',
    therapeutic_class: 'Beta-lactam Antibacterial',
    atc_code: 'J01CR02',
    is_antibiotic: true,
    antibiotic_class: 'Penicillins',
    awarre_category: 'Access',
    manufacturer: 'GlaxoSmithKline',
    status: 'active',
  },
  {
    id: 'med-2',
    generic_name: 'Ceftriaxone',
    brand_name: 'Rocephin',
    active_ingredients: 'Ceftriaxone Sodium',
    strength: '1 g',
    dosage_form: 'Injection',
    route: 'Intravenous',
    therapeutic_class: 'Third-generation Cephalosporin',
    atc_code: 'J01DD04',
    is_antibiotic: true,
    antibiotic_class: 'Cephalosporins',
    awarre_category: 'Watch',
    manufacturer: 'Roche Pharmaceuticals',
    status: 'active',
  },
  {
    id: 'med-3',
    generic_name: 'Ciprofloxacin',
    brand_name: 'Ciprobay',
    active_ingredients: 'Ciprofloxacin Hydrochloride',
    strength: '500 mg',
    dosage_form: 'Tablet',
    route: 'Oral',
    therapeutic_class: 'Fluoroquinolones',
    atc_code: 'J01MA02',
    is_antibiotic: true,
    antibiotic_class: 'Fluoroquinolones',
    awarre_category: 'Watch',
    manufacturer: 'Bayer Healthcare',
    status: 'active',
  },
  {
    id: 'med-4',
    generic_name: 'Meropenem',
    brand_name: 'Meronem',
    active_ingredients: 'Meropenem Trihydrate',
    strength: '1 g',
    dosage_form: 'Injection',
    route: 'Intravenous',
    therapeutic_class: 'Carbapenems',
    atc_code: 'J01DH02',
    is_antibiotic: true,
    antibiotic_class: 'Carbapenems',
    awarre_category: 'Watch',
    manufacturer: 'Pfizer Global',
    status: 'active',
  },
  {
    id: 'med-5',
    generic_name: 'Azithromycin',
    brand_name: 'Zithromax',
    active_ingredients: 'Azithromycin Dihydrate',
    strength: '500 mg',
    dosage_form: 'Tablet',
    route: 'Oral',
    therapeutic_class: 'Macrolides',
    atc_code: 'J01FA10',
    is_antibiotic: true,
    antibiotic_class: 'Macrolides',
    awarre_category: 'Watch',
    manufacturer: 'Pfizer Global',
    status: 'active',
  },
  {
    id: 'med-6',
    generic_name: 'Linezolid',
    brand_name: 'Zyvox',
    active_ingredients: 'Linezolid',
    strength: '600 mg',
    dosage_form: 'Tablet',
    route: 'Oral',
    therapeutic_class: 'Oxazolidinones',
    atc_code: 'J01XX08',
    is_antibiotic: true,
    antibiotic_class: 'Oxazolidinones',
    awarre_category: 'Reserve',
    manufacturer: 'Pfizer Global',
    status: 'active',
  },
  {
    id: 'med-7',
    generic_name: 'Colistin (Polymyxin E)',
    brand_name: 'Colomycin',
    active_ingredients: 'Colistimethate Sodium',
    strength: '1 Million IU',
    dosage_form: 'Injection',
    route: 'Intravenous',
    therapeutic_class: 'Polymyxins',
    atc_code: 'J01XB01',
    is_antibiotic: true,
    antibiotic_class: 'Polymyxins',
    awarre_category: 'Reserve',
    manufacturer: 'Forest Laboratories',
    status: 'active',
  },
  {
    id: 'med-8',
    generic_name: 'Paracetamol',
    brand_name: 'Panadol',
    active_ingredients: 'Acetaminophen',
    strength: '500 mg',
    dosage_form: 'Tablet',
    route: 'Oral',
    therapeutic_class: 'Analgesics / Antipyretics',
    atc_code: 'N02BE01',
    is_antibiotic: false,
    manufacturer: 'GSK Consumer',
    status: 'active',
  },
];

export const INITIAL_BATCHES: MedicineBatch[] = [
  {
    id: 'bat-1',
    medicine_id: 'med-1',
    facility_id: 'fac-4',
    batch_number: 'AUG-2024-B88',
    manufacture_date: '2024-01-10',
    expiry_date: '2026-06-30',
    initial_quantity: 5000,
    current_quantity: 3420,
    verification_status: 'Verified',
    recall_status: 'Normal',
    verification_source: 'National Drug Regulatory Authority GS1',
    notes: 'Verified safe for dispensing',
  },
  {
    id: 'bat-2',
    medicine_id: 'med-2',
    facility_id: 'fac-1',
    batch_number: 'CTX-2024-V12',
    manufacture_date: '2024-03-15',
    expiry_date: '2026-03-31',
    initial_quantity: 2000,
    current_quantity: 850,
    verification_status: 'Verified',
    recall_status: 'Normal',
    verification_source: 'Hospital Pharmacy QC',
    notes: 'Routine batch in ICU supply',
  },
  {
    id: 'bat-3',
    medicine_id: 'med-4',
    facility_id: 'fac-1',
    batch_number: 'MER-2023-X91',
    manufacture_date: '2023-08-01',
    expiry_date: '2025-08-31',
    initial_quantity: 1200,
    current_quantity: 420,
    verification_status: 'Verified',
    recall_status: 'Normal',
    verification_source: 'Manufacturer Certificate of Analysis',
    notes: 'High surveillance priority',
  },
  {
    id: 'bat-4',
    medicine_id: 'med-3',
    facility_id: 'fac-4',
    batch_number: 'CIP-2023-EXP',
    manufacture_date: '2023-01-10',
    expiry_date: '2024-12-31',
    initial_quantity: 1500,
    current_quantity: 140,
    verification_status: 'Expired',
    recall_status: 'Normal',
    verification_source: 'Internal Expiry Check',
    notes: 'Flagged as expired batch - quarantine immediately',
  },
  {
    id: 'bat-5',
    medicine_id: 'med-5',
    facility_id: 'fac-4',
    batch_number: 'AZI-2024-SUSP',
    manufacture_date: '2024-05-20',
    expiry_date: '2026-11-30',
    initial_quantity: 800,
    current_quantity: 780,
    verification_status: 'Suspicious',
    recall_status: 'Quarantined',
    verification_source: 'Packaging Discrepancy Signal',
    notes: 'Tamper seal irregularity reported during inventory intake',
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-1',
    organization_id: 'org-1',
    facility_id: 'fac-1',
    prescriber_id: 'usr-2',
    patient_reference: 'PAT-88192-A',
    encounter_reference: 'ENC-2024-091',
    prescription_date: '2024-09-18T10:30:00Z',
    clinical_indication: 'Hospital-Acquired Pneumonia with sepsis criteria',
    status: 'dispensed',
    items: [
      {
        id: 'rxi-1',
        prescription_id: 'rx-1',
        medicine_id: 'med-2',
        dose: '1 g IV',
        frequency: 'BID',
        route: 'Intravenous',
        duration_days: 7,
        quantity: 14,
        indication_category: 'Respiratory',
      },
      {
        id: 'rxi-2',
        prescription_id: 'rx-1',
        medicine_id: 'med-8',
        dose: '500 mg',
        frequency: 'TID PRN',
        route: 'Oral',
        duration_days: 3,
        quantity: 9,
      },
    ],
  },
  {
    id: 'rx-2',
    organization_id: 'org-1',
    facility_id: 'fac-3',
    prescriber_id: 'usr-2',
    patient_reference: 'PAT-90142-C',
    encounter_reference: 'ENC-2024-114',
    prescription_date: '2024-09-19T14:15:00Z',
    clinical_indication: 'Complicated Intra-Abdominal Sepsis',
    status: 'active',
    items: [
      {
        id: 'rxi-3',
        prescription_id: 'rx-2',
        medicine_id: 'med-4',
        dose: '1 g IV Infusion',
        frequency: 'TID',
        route: 'Intravenous',
        duration_days: 10,
        quantity: 30,
        indication_category: 'Sepsis',
      },
    ],
  },
  {
    id: 'rx-3',
    organization_id: 'org-1',
    facility_id: 'fac-1',
    prescriber_id: 'usr-2',
    patient_reference: 'PAT-77210-K',
    encounter_reference: 'ENC-2024-042',
    prescription_date: '2024-09-20T08:45:00Z',
    clinical_indication: 'Acute Uncomplicated Pyelonephritis',
    status: 'active',
    items: [
      {
        id: 'rxi-4',
        prescription_id: 'rx-3',
        medicine_id: 'med-3',
        dose: '500 mg Oral',
        frequency: 'BID',
        route: 'Oral',
        duration_days: 7,
        quantity: 14,
        indication_category: 'UTI',
      },
    ],
  },
];

export const INITIAL_DISPENSING: DispensingRecord[] = [
  {
    id: 'dsp-1',
    organization_id: 'org-1',
    facility_id: 'fac-4',
    prescription_id: 'rx-1',
    medicine_id: 'med-2',
    batch_id: 'bat-2',
    pharmacist_id: 'usr-3',
    patient_reference: 'PAT-88192-A',
    quantity: 14,
    dispensed_at: '2024-09-18T11:20:00Z',
    repeat_flag: false,
    verification_status: 'Verified',
    notes: 'Batch CTX-2024-V12 verified against cold-chain storage log',
  },
  {
    id: 'dsp-2',
    organization_id: 'org-1',
    facility_id: 'fac-4',
    prescription_id: 'rx-1',
    medicine_id: 'med-8',
    batch_id: 'bat-1',
    pharmacist_id: 'usr-3',
    patient_reference: 'PAT-88192-A',
    quantity: 9,
    dispensed_at: '2024-09-18T11:22:00Z',
    repeat_flag: false,
    verification_status: 'Verified',
  },
];

export const INITIAL_ORGANISMS: Organism[] = [
  {
    id: 'org-ecoli',
    name: 'Escherichia coli',
    scientific_name: 'Escherichia coli',
    category: 'Gram-negative bacilli',
    gram_stain: 'Gram-negative',
    who_priority: 'Critical',
    status: 'active',
  },
  {
    id: 'org-kleb',
    name: 'Klebsiella pneumoniae',
    scientific_name: 'Klebsiella pneumoniae',
    category: 'Gram-negative bacilli',
    gram_stain: 'Gram-negative',
    who_priority: 'Critical',
    status: 'active',
  },
  {
    id: 'org-pseud',
    name: 'Pseudomonas aeruginosa',
    scientific_name: 'Pseudomonas aeruginosa',
    category: 'Gram-negative bacilli',
    gram_stain: 'Gram-negative',
    who_priority: 'Critical',
    status: 'active',
  },
  {
    id: 'org-acin',
    name: 'Acinetobacter baumannii',
    scientific_name: 'Acinetobacter baumannii',
    category: 'Gram-negative bacilli',
    gram_stain: 'Gram-negative',
    who_priority: 'Critical',
    status: 'active',
  },
  {
    id: 'org-staph',
    name: 'Staphylococcus aureus',
    scientific_name: 'Staphylococcus aureus',
    category: 'Gram-positive cocci',
    gram_stain: 'Gram-positive',
    who_priority: 'High',
    status: 'active',
  },
];

export const INITIAL_SPECIMENS: Specimen[] = [
  {
    id: 'spc-1',
    organization_id: 'org-1',
    laboratory_id: 'fac-2',
    patient_reference: 'PAT-88192-A',
    specimen_type: 'Sputum',
    collected_at: '2024-09-17T08:00:00Z',
    received_at: '2024-09-17T09:15:00Z',
    quality_status: 'Adequate',
    notes: 'Purulent sputum from ICU ventilator patient',
  },
  {
    id: 'spc-2',
    organization_id: 'org-1',
    laboratory_id: 'fac-2',
    patient_reference: 'PAT-90142-C',
    specimen_type: 'Blood',
    collected_at: '2024-09-18T06:30:00Z',
    received_at: '2024-09-18T07:45:00Z',
    quality_status: 'Adequate',
    notes: 'Blood culture x2 sets collected prior to antibiotic initiation',
  },
  {
    id: 'spc-3',
    organization_id: 'org-1',
    laboratory_id: 'fac-2',
    patient_reference: 'PAT-77210-K',
    specimen_type: 'Urine',
    collected_at: '2024-09-19T07:10:00Z',
    received_at: '2024-09-19T08:20:00Z',
    quality_status: 'Adequate',
    notes: 'Clean-catch midstream urine',
  },
];

export const INITIAL_SUSCEPTIBILITY: SusceptibilityResult[] = [
  {
    id: 'ast-1',
    specimen_id: 'spc-1',
    organism_id: 'org-kleb',
    antibiotic_id: 'med-2', // Ceftriaxone
    result: 'Resistant',
    mic_value: '>= 32 ug/mL',
    interpretation: 'R',
    tested_at: '2024-09-18T16:00:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
    notes: 'ESBL screen positive via double-disk synergy test',
  },
  {
    id: 'ast-2',
    specimen_id: 'spc-1',
    organism_id: 'org-kleb',
    antibiotic_id: 'med-4', // Meropenem
    result: 'Susceptible',
    mic_value: '<= 0.25 ug/mL',
    interpretation: 'S',
    tested_at: '2024-09-18T16:00:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
  },
  {
    id: 'ast-3',
    specimen_id: 'spc-1',
    organism_id: 'org-kleb',
    antibiotic_id: 'med-3', // Ciprofloxacin
    result: 'Resistant',
    mic_value: '>= 4 ug/mL',
    interpretation: 'R',
    tested_at: '2024-09-18T16:00:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
  },
  {
    id: 'ast-4',
    specimen_id: 'spc-2',
    organism_id: 'org-ecoli',
    antibiotic_id: 'med-2', // Ceftriaxone
    result: 'Resistant',
    mic_value: '>= 16 ug/mL',
    interpretation: 'R',
    tested_at: '2024-09-19T14:30:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
  },
  {
    id: 'ast-5',
    specimen_id: 'spc-2',
    organism_id: 'org-ecoli',
    antibiotic_id: 'med-4', // Meropenem
    result: 'Susceptible',
    mic_value: '<= 0.5 ug/mL',
    interpretation: 'S',
    tested_at: '2024-09-19T14:30:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
  },
  {
    id: 'ast-6',
    specimen_id: 'spc-3',
    organism_id: 'org-ecoli',
    antibiotic_id: 'med-3', // Ciprofloxacin
    result: 'Resistant',
    mic_value: '>= 8 ug/mL',
    interpretation: 'R',
    tested_at: '2024-09-20T11:00:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
  },
  {
    id: 'ast-7',
    specimen_id: 'spc-3',
    organism_id: 'org-ecoli',
    antibiotic_id: 'med-1', // Augmentin
    result: 'Intermediate',
    mic_value: '16/8 ug/mL',
    interpretation: 'I',
    tested_at: '2024-09-20T11:00:00Z',
    guideline_version: 'CLSI M100-ED33',
    quality_status: 'Valid',
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-1',
    organization_id: 'org-1',
    facility_id: 'fac-1',
    signal_type: 'resistance_surge',
    severity: 'Critical',
    title: 'Signal detected: Ceftriaxone Resistance Surge in Klebsiella pneumoniae',
    description: 'Microbiology surveillance detected a 38.7% resistance surge compared to 6-month baseline across Mayo Memorial ICU cultures.',
    detected_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    period_start: new Date(Date.now() - 30 * 86400 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    observed_value: 64.2,
    baseline_value: 46.3,
    change_percent: 38.66,
    affected_entity_type: 'organism',
    affected_entity_id: 'org-kleb',
    status: 'Investigating',
    assigned_to: 'usr-5',
    detection_rule_id: 'RULE-AMR-SURGE-01',
    detection_rule_version: '1.0.0',
    evidence: [
      {
        id: 'ev-1',
        alert_id: 'alt-1',
        source_type: 'susceptibility_results',
        source_id: 'ast-1',
        statistical_payload: {
          tested_count: 22,
          resistant_count: 14,
          p_value: 0.038,
          confidence_interval: '52.1% - 75.8%',
        },
      },
    ],
  },
  {
    id: 'alt-2',
    organization_id: 'org-1',
    facility_id: 'fac-4',
    signal_type: 'batch_issue',
    severity: 'High',
    title: 'Batch signal: Expired Antibiotic Batch CIP-2023-EXP Active in Pharmacy Inventory',
    description: 'Batch verification engine detected active inventory (140 units) of expired Ciprofloxacin 500mg tablets in Regional Pharmacy Hub 01.',
    detected_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    period_start: new Date(Date.now() - 7 * 86400 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    observed_value: 140,
    baseline_value: 0,
    change_percent: 100,
    affected_entity_type: 'batch',
    affected_entity_id: 'bat-4',
    status: 'Acknowledged',
    assigned_to: 'usr-3',
    detection_rule_id: 'RULE-BATCH-EXP-02',
    detection_rule_version: '1.0.0',
  },
  {
    id: 'alt-3',
    organization_id: 'org-1',
    facility_id: 'fac-1',
    signal_type: 'unusual_usage',
    severity: 'Medium',
    title: 'Pattern observed: Intravenous Meropenem Dispensing Spike in Surgical Ward',
    description: 'Observed 52.4% increase in intravenous Meropenem dispensing over 14-day baseline without corresponding rise in confirmed sepsis cultures.',
    detected_at: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    period_start: new Date(Date.now() - 14 * 86400 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    observed_value: 345,
    baseline_value: 226,
    change_percent: 52.65,
    affected_entity_type: 'medicine',
    affected_entity_id: 'med-4',
    status: 'New',
    detection_rule_id: 'RULE-USAGE-SPIKE-03',
    detection_rule_version: '1.0.0',
  },
  {
    id: 'alt-4',
    organization_id: 'org-1',
    facility_id: 'fac-2',
    signal_type: 'data_quality',
    severity: 'Low',
    title: 'Preliminary surveillance finding: Laboratory AST Records Missing MIC Numeric Values',
    description: '12 out of 115 recent susceptibility records entered with disk-diffusion qualitative results without recorded numeric MIC values.',
    detected_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    period_start: new Date(Date.now() - 7 * 86400 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    observed_value: 12,
    baseline_value: 0,
    change_percent: 10.43,
    affected_entity_type: 'facility',
    affected_entity_id: 'fac-2',
    status: 'New',
    detection_rule_id: 'RULE-DQ-MIC-04',
    detection_rule_version: '1.0.0',
  },
];

export const INITIAL_INVESTIGATIONS: Investigation[] = [
  {
    id: 'inv-1',
    alert_id: 'alt-1',
    organization_id: 'org-1',
    investigator_id: 'usr-5',
    status: 'In Progress',
    findings: 'Preliminary surveillance finding: 14 out of 22 Klebsiella isolates in surgical ICU exhibit ESBL phenotype with elevated Ceftriaxone MIC (>16 ug/mL). Cross-referencing environmental swabs and nurse staffing ratios.',
    action_taken: 'Initiated contact precautions audit and notified Antimicrobial Stewardship Committee for regimen switch review.',
    started_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    notes: [
      {
        id: 'note-1',
        investigation_id: 'inv-1',
        author_id: 'usr-5',
        note: 'Reviewed 30-day antibiogram with Dr. Asad from Microbiology. Denominator is 22 non-duplicate clinical isolates. Signal is statistically notable (p < 0.05).',
        created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
      {
        id: 'note-2',
        investigation_id: 'inv-1',
        author_id: 'usr-4',
        note: 'Microbiology lab confirms EUCAST disk diffusion and automated VITEK-2 AST profiles match clonal pattern. Recommending stewardship alert to prescribers.',
        created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      },
    ],
  },
];

export const INITIAL_REPORTS: SurveillanceReport[] = [
  {
    id: 'rep-1',
    organization_id: 'org-1',
    created_by: 'usr-5',
    title: 'Monthly Antimicrobial Resistance & Consumption Surveillance Report (August 2024)',
    type: 'monthly_surveillance',
    period_start: '2024-08-01',
    period_end: '2024-08-31',
    filters_json: { organization_id: 'org-1' },
    status: 'Completed',
    summary_markdown: `### Executive Summary
Surveillance data for August 2024 across 4 network facilities indicates an overall antibiotic resistance rate of **34.2%** across 480 tested isolates. 
A critical signal was detected in *Klebsiella pneumoniae* ceftriaxone resistance, rising from 46.3% baseline to 64.2% (observed in 22 isolates).

### Key Indicators
- Total Prescriptions Monitored: **1,420**
- Antibiotic Dispensing Volume: **3,890 units** (Watch category: 58.4%, Access category: 37.1%, Reserve: 4.5%)
- Susceptibility Tests Completed: **480 isolates**
- Active Critical Alerts: **1** (Investigating)

### Limitations
Calculations are restricted to reported microbiology cultures with valid QC status. Outpatient empiric prescriptions without laboratory cultures are not captured in the denominator.`,
    created_at: '2024-09-01T12:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    organization_id: 'org-1',
    actor_id: 'usr-3',
    action: 'verify_batch',
    entity_type: 'medicine_batches',
    entity_id: 'bat-1',
    new_values: { verification_status: 'Verified', batch: 'AUG-2024-B88' },
    ip_address: '192.168.10.45',
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-2',
    organization_id: 'org-1',
    actor_id: 'usr-5',
    action: 'add_investigation_note',
    entity_type: 'investigations',
    entity_id: 'inv-1',
    new_values: { alert_id: 'alt-1', note_length: 135 },
    ip_address: '192.168.10.82',
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-3',
    organization_id: 'org-1',
    actor_id: 'usr-2',
    action: 'create_prescription',
    entity_type: 'prescriptions',
    entity_id: 'rx-1',
    new_values: { patient_reference: 'PAT-88192-A', items_count: 2 },
    ip_address: '192.168.12.11',
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_DATA_QUALITY: DataQualityIssue[] = [
  {
    id: 'dq-1',
    organization_id: 'org-1',
    entity_type: 'susceptibility_results',
    entity_id: 'ast-7',
    issue_type: 'missing_interpretation',
    severity: 'Medium',
    description: 'Phenotypic breakpoint discrepancy detected for Amoxicillin/Clavulanate against E. coli isolate.',
    status: 'Open',
    created_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
  },
  {
    id: 'dq-2',
    organization_id: 'org-1',
    entity_type: 'medicine_batches',
    entity_id: 'bat-4',
    issue_type: 'invalid_expiry',
    severity: 'High',
    description: 'Active inventory quantity recorded for expired batch CIP-2023-EXP without automatic quarantine flag.',
    status: 'Open',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_REGIONS: GeographicRegion[] = [
  { id: 'reg-lhr', name: 'Lahore Metropolitan', country: 'Pakistan', lat: 31.5204, lng: 74.3587, total_facilities: 14, resistance_rate: 38.6, utilization_units: 14200, active_alerts: 4, status: 'Critical' },
  { id: 'reg-khi', name: 'Karachi Central & South', country: 'Pakistan', lat: 24.8607, lng: 67.0011, total_facilities: 22, resistance_rate: 42.1, utilization_units: 28400, active_alerts: 6, status: 'Critical' },
  { id: 'reg-isb', name: 'Islamabad Capital Territory', country: 'Pakistan', lat: 33.6844, lng: 73.0479, total_facilities: 8, resistance_rate: 26.4, utilization_units: 8900, active_alerts: 1, status: 'Stable' },
  { id: 'reg-rwp', name: 'Rawalpindi Division', country: 'Pakistan', lat: 33.5651, lng: 73.0169, total_facilities: 9, resistance_rate: 31.8, utilization_units: 11200, active_alerts: 2, status: 'Watch' },
  { id: 'reg-psh', name: 'Peshawar Valley', country: 'Pakistan', lat: 34.0151, lng: 71.5249, total_facilities: 7, resistance_rate: 35.2, utilization_units: 7800, active_alerts: 3, status: 'Watch' },
  { id: 'reg-mul', name: 'Multan Southern Hub', country: 'Pakistan', lat: 30.1575, lng: 71.5249, total_facilities: 6, resistance_rate: 33.9, utilization_units: 6400, active_alerts: 2, status: 'Watch' },
];

export const INITIAL_PRESCRIBER_ANALYTICS: PrescriberAnalytics[] = [
  {
    id: 'pra-1',
    doctor_name: 'Dr. Sarah Farooq',
    prescriber_name: 'Dr. Sarah Farooq',
    specialty: 'Pulmonology / Critical Care',
    department: 'Pulmonology / Critical Care',
    facility: 'Mayo Memorial Hospital',
    facility_name: 'Mayo Memorial Hospital',
    prescriptions_count: 312,
    total_prescriptions: 312,
    antibiotic_rate: 68.2,
    watch_reserve_ratio: 54.1,
    compliance_score: 88,
    guideline_adherence_pct: 92,
    high_risk_alerts_count: 1,
    aware_distribution: { Access: 62, Watch: 30, Reserve: 8 },
  },
  {
    id: 'pra-2',
    doctor_name: 'Dr. Kamran Akram',
    prescriber_name: 'Dr. Kamran Akram',
    specialty: 'General Surgery',
    department: 'General Surgery',
    facility: 'Allama Iqbal Complex',
    facility_name: 'Allama Iqbal Complex',
    prescriptions_count: 245,
    total_prescriptions: 245,
    antibiotic_rate: 79.5,
    watch_reserve_ratio: 66.8,
    compliance_score: 72,
    guideline_adherence_pct: 78,
    high_risk_alerts_count: 4,
    aware_distribution: { Access: 48, Watch: 42, Reserve: 10 },
  },
  {
    id: 'pra-3',
    doctor_name: 'Dr. Nadia Hashmi',
    prescriber_name: 'Dr. Nadia Hashmi',
    specialty: 'Internal Medicine',
    department: 'Internal Medicine',
    facility: 'Mayo Memorial Hospital',
    facility_name: 'Mayo Memorial Hospital',
    prescriptions_count: 290,
    total_prescriptions: 290,
    antibiotic_rate: 51.0,
    watch_reserve_ratio: 38.2,
    compliance_score: 94,
    guideline_adherence_pct: 95,
    high_risk_alerts_count: 0,
    aware_distribution: { Access: 74, Watch: 22, Reserve: 4 },
  },
  {
    id: 'pra-4',
    doctor_name: 'Dr. Faisal Hayat',
    prescriber_name: 'Dr. Faisal Hayat',
    specialty: 'Urology / Surgery',
    department: 'Urology',
    facility: 'Allama Iqbal Complex',
    facility_name: 'Allama Iqbal Complex',
    prescriptions_count: 188,
    total_prescriptions: 188,
    antibiotic_rate: 84.0,
    watch_reserve_ratio: 71.5,
    compliance_score: 69,
    guideline_adherence_pct: 71,
    high_risk_alerts_count: 5,
    aware_distribution: { Access: 42, Watch: 46, Reserve: 12 },
  },
];

export const INITIAL_INDICATIONS: IndicationBreakdown[] = [
  { category: 'Respiratory (CAP / HAP)', prescriptions: 580, top_antibiotic: 'Ceftriaxone', avg_duration_days: 7, resistance_rate: 41.2 },
  { category: 'Urinary Tract Infections (UTI)', prescriptions: 420, top_antibiotic: 'Ciprofloxacin', avg_duration_days: 5, resistance_rate: 52.8 },
  { category: 'Severe Sepsis / Bacteremia', prescriptions: 240, top_antibiotic: 'Meropenem', avg_duration_days: 10, resistance_rate: 28.5 },
  { category: 'Surgical Prophylaxis', prescriptions: 360, top_antibiotic: 'Cefazolin / Augmentin', avg_duration_days: 2, resistance_rate: 18.0 },
  { category: 'Intra-Abdominal Sepsis', prescriptions: 190, top_antibiotic: 'Meropenem + Metronidazole', avg_duration_days: 8, resistance_rate: 34.0 },
];

export const INITIAL_CONNECTORS: SystemConnector[] = [
  {
    id: 'conn-1',
    name: 'Mayo Memorial Hospital LIS (ASTM 1394)',
    type: 'LIS_ASTM',
    protocol: 'ASTM E1394 / E1381 RS-232/TCP',
    endpoint: 'tcp://192.168.10.45:5000/astm',
    status: 'Online',
    records_processed_24h: 1840,
    records_synced: 1840,
    error_rate: 0.1,
    last_sync: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    latency_ms: 45,
  },
  {
    id: 'conn-2',
    name: 'National Regulatory GS1 Verification Gateway',
    type: 'GS1_EPCIS',
    protocol: 'GS1 Digital Link / EPCIS 2.0 REST',
    endpoint: 'https://gateway.gs1pk.org/api/v2/epcis',
    status: 'Online',
    records_processed_24h: 3420,
    records_synced: 3420,
    error_rate: 0.0,
    last_sync: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    latency_ms: 120,
  },
  {
    id: 'conn-3',
    name: 'Regional EHR HL7 FHIR R4 Ingestion Node',
    type: 'HL7_FHIR',
    protocol: 'HL7 FHIR R4 JSON REST',
    endpoint: 'https://ehr.punjabhealth.gov.pk/fhir/r4',
    status: 'Online',
    records_processed_24h: 8920,
    records_synced: 8920,
    error_rate: 0.3,
    last_sync: new Date().toISOString(),
    latency_ms: 82,
  },
  {
    id: 'conn-4',
    name: 'National DHIS-2 AMR Surveillance Uplink',
    type: 'DHIS2_SURVEILLANCE',
    protocol: 'DHIS-2 DataValueSets Webhook API',
    endpoint: 'https://dhis2.nih.org.pk/api/dataValueSets',
    status: 'Degraded',
    records_processed_24h: 420,
    records_synced: 420,
    error_rate: 2.4,
    last_sync: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    latency_ms: 540,
  },
];

export const INITIAL_BACKGROUND_JOBS: BackgroundJob[] = [
  {
    id: 'job-1',
    name: 'Deterministic AMR Surge Rule Engine',
    schedule: 'Every 15 minutes',
    last_run: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    next_run: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    status: 'Success',
    duration_sec: 4.2,
    duration_ms: 420,
    records_evaluated: 480,
  },
  {
    id: 'job-2',
    name: 'Batch Expiry & Cold-Chain Anomaly Check',
    schedule: 'Hourly at :00',
    last_run: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    next_run: new Date(Date.now() + 32 * 60 * 1000).toISOString(),
    status: 'Success',
    duration_sec: 1.8,
    duration_ms: 180,
    records_evaluated: 1420,
  },
  {
    id: 'job-3',
    name: 'Longitudinal Antibiogram Matrix Aggregator',
    schedule: 'Daily at 00:00 UTC',
    last_run: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    next_run: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    status: 'Success',
    duration_sec: 18.4,
    duration_ms: 1840,
    records_evaluated: 18400,
  },
  {
    id: 'job-4',
    name: 'Automated Data Quality & Hygiene Validator',
    schedule: 'Every 6 hours',
    last_run: new Date(Date.now() - 3600 * 1000).toISOString(),
    next_run: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    status: 'Success',
    duration_sec: 6.1,
    duration_ms: 610,
    records_evaluated: 3200,
  },
];


